galaxy_info:
  author: ElastiFlow Engineering Team <engineering@elastiflow.com>
  description: Ansible collection for ElastiFlow NetObserv roles and playbooks.
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - "jammy"
        - "noble"
