argument_specs:
  main:
    short_description: |
      NetObserv Flow role, configuring flow collection, enrichment, and output for ElastiFlow.
    description: |
      NetObserv Flow role, configuring flow collection, enrichment, and output for ElastiFlow.
      Please see full documentation at https://docs.elastiflow.com/flowcoll/configuration

      #### License

      You need explicitly accept the ElastiFlow license to use NetObserv Flow.
      ```yaml
      netobserv_flow_config_values:
          EF_LICENSE_ACCEPTED: true
      ```

      If you have a license key, please add it to the playbook vars (consider using [Ansible Vault](https://docs.ansible.com/ansible/latest/vault_guide/index.html) to encrypt the license key)
      ```yaml
      netobserv_flow_license:
          license_key: "${LICENSE_KEY}"
          account_id: "${ACCOUNT_ID}"
      ```

      #### User Defined data

      For various features you may need to upload user-defined data, for example for:

      - [User-defined metadata enrichment](https://docs.elastiflow.com/snmpcoll/configuration/enrichment-options-1/enrich_ip_udm/enrich_ip_udm#ef_processor_enrich_ipaddr_metadata_userdef_path)
      - [GeoIP include/exclude](https://docs.elastiflow.com/flowcoll/configuration/enrichment-options/ip-address-enrichment/enrich_ip_maxmind#ef_processor_enrich_ipaddr_maxmind_geoip_inclexcl_path)

      The role does not provide a mechanism for uploading local files, nor does it allow defining inline data for those features. However, you may use the following example task (`pre_tasks`) to upload those files from your Ansible control node to the managed host.

      ```yaml
        post_tasks:
          - name: Copy NetObserv Flow User-Defined Metadata IP enrichment config
            ansible.builtin.copy:
              src: "{{ playbook_dir }}/ipaddrs-test.yaml"
              dest: "/etc/elastiflow/metadata/ipaddrs.yml"
              mode: "0644"
              backup: true
            notify:
              - Restart NetObserv Flow
      ```

      #### Sample flows from the host

      You may ingest flows from the server the netobserv-flow is running on by setting-up a [softflowd](https://github.com/irino/softflowd) (available in Debian/Ubuntu repos).
      You may install it manually or use following task (full examples may be found in the `examples` dir)
      ```yaml
      tasks:
        - name: Install softflowd
          notify: Restart softflowd
          when: ansible_os_family | lower == "debian"
          block:
            - name: Install softflowd
              ansible.builtin.package:
                name: softflowd
            - name: Configure softflowd
              # -n localhost:port should be identical to `netobserv_flow_config_input_flow.server_udp_port` netobserv-flow var, default is 9995
              # More details on the config here: https://docs.elastiflow.com/additional-resources-reference-articles/guides/configuring-flow-logs-on-devices/device_flow_openwrt_softflowd
              ansible.builtin.copy:
                dest: /etc/softflowd/default.conf
                backup: true
                owner: root
                group: root
                mode: "0644"
                content: |
                  interface='any'
                  # -n localhost:port should be identical to `netobserv_flow_config_input_flow.server_udp_port` netobserv-flow var, default is 9995
                  # Run `softflowd -h` for command-line options details.
                  # More details on the config here: https://docs.elastiflow.com/additional-resources-reference-articles/guides/configuring-flow-logs-on-devices/device_flow_openwrt_softflowd
                  options='-n localhost:9995
                    -v 9
                    -L 255
                    -T ether
                    -6
                    -s 1
                    -t tcp.fin=10
                    -t expint=10
                    -t icmp=20
                    -t tcp=60
                    -t maxlife=60
                    -t general=60
                    -t udp=60'
      ```

      ## Upgrade notes

      ### v0.4.1 -> v0.5.x

      Refer to the [Pull Request](https://github.com/elastiflow/ansible-collection-netobserv/pull/29) for the full list of changes.

      - License needs to be explicitly accepted via `netobserv_flow_config_values` (`netobserv_flow_license.accepted`) is removed
        ```yaml
        netobserv_flow_config_values:
          EF_LICENSE_ACCEPTED: true
        ```
      - Top-level `netobserv_flow_dashboards` var is removed, OpenSearch and ElasticSearch import dashboard options are now in the `netobserv_flow_output_elasticsearch.dashboards`/`netobserv_flow_output_opensearch.dashboards`
      - Update `netobserv_flow_output_elasticsearch`/`netobserv_flow_output_opensearch` variables (refer the role's readme for the details)
      - Fill all values that are not present in the "complex" Ansible vars to the `netobserv_flow_config_values` dict.

      Please see the example playbooks changes for reference:
      - [Example ElasticSearch playbook](https://github.com/elastiflow/ansible-collection-netobserv/pull/29/changes#diff-34614fb12163c3dbf55c7dcc616780f464787d64c58e5dade1f45f10c24c7641)
      - [Example OpensearchSearch playbook](https://github.com/elastiflow/ansible-collection-netobserv/pull/29/changes#diff-858969464991d766dda4f3ed2f0503b0bb0b17dac21f331e2e2c0174ff5a0909)

      The safest way to upgrade is:
      1. Backup `/etc/elastiflow` directory
      2. Copy `/etc/elastiflow/flowcoll.yml` values under the the `netobserv_flow_config_values` Ansible variable

    options:
      netobserv_flow_install:
        type: bool
        default: true
        description: |
          Whether to install NetObserv Flow.

      netobserv_flow_version:
        type: str
        default: "1:7.20.0-1"
        description: |
          NetObserv Flow version to install.

      netobserv_flow_config_dir:
        type: str
        default: "/etc/elastiflow"
        description: |
          Directory for NetObserv Flow configuration files.

      netobserv_flow_config_file:
        type: str
        default: "{{ netobserv_flow_config_dir }}/flowcoll.yml"
        description: |
          Main configuration file for NetObserv Flow.

      netobserv_flow_license:
        type: dict
        description: |
          License configuration for NetObserv Flow collector.
          See: https://docs.elastiflow.com/flowcoll/configuration/config_gen/license
          ***defaults_prefix:"__"***
        options:
          account_id:
            type: str
            default: null
            description: ElastiFlow account ID.
          key:
            type: str
            default: null
            description: ElastiFlow license key.

      netobserv_flow_output_elasticsearch:
        type: dict
        description: |
          ElasticSearch output configuration.
          See: https://docs.elastiflow.com/flowcoll/configuration/outputs/output_elasticsearch/elastic-configuration-options
          ***defaults_prefix:"__"***
        options:
          enable:
            type: bool
            default: false
            description: Enable output to ElasticSearch.
          ecs:
            type: dict
            description: Elastic Common Schema configuration.
            options:
              enable:
                type: bool
                default: false
                description: Enable Elastic Common Schema.
          addresses:
            type: str
            default: "127.0.0.1:9200"
            description: ElasticSearch node addresses.
          username:
            type: str
            default: "elastic"
            description: Username for ElasticSearch.
          password:
            type: str
            description: Password for ElasticSearch.
          tls:
            type: dict
            description: TLS configuration for ElasticSearch output.
            options:
              enable:
                type: bool
                default: false
                description: Enable TLS.
              skip_verification:
                type: bool
                default: false
                description: Skip certificate verification.
              ca_cert_filepath:
                type: str
                default: ""
                description: Path to CA certificate.

          dashboards:
            type: dict
            description: |
              ElasticSearch dashboard import configuration.
              See: https://docs.elastiflow.com/flowcoll/configuration/outputs/output_elasticsearch
            options:
              enable:
                type: bool
                default: false
                description: Enable ElasticSearch dashboard import.
              url:
                type: str
                default: "https://raw.githubusercontent.com/elastiflow/elastiflow_for_elasticsearch/master/kibana/flow/kibana-8.14.x-flow-codex.ndjson"
                description: URL for Kibana dashboard.
              override:
                type: bool
                default: true
                description: Override existing dashboards.
              kibana_url:
                type: str
                default: "http://127.0.0.1:5601"
                description: Kibana server URL.
              tls:
                type: dict
                description: TLS configuration for dashboard import.
                options:
                  validate_certs:
                    type: bool
                    default: false
                    description: Validate TLS certificates.
                  client_cert:
                    type: str
                    default: null
                    description: Path to client certificate.
                  client_key:
                    type: str
                    default: null
                    description: Path to client key.

      netobserv_flow_output_opensearch:
        type: dict
        description: |
          OpenSearch output configuration.
          See: https://docs.elastiflow.com/flowcoll/configuration/outputs/output_opensearch/opensearch-configuration-options
          ***defaults_prefix:"__"***
        options:
          enable:
            type: bool
            default: false
            description: Enable output to OpenSearch.
          ecs:
            type: dict
            description: Elastic Common Schema configuration.
            options:
              enable:
                type: bool
                default: false
                description: Enable Elastic Common Schema.
          addresses:
            type: str
            default: "127.0.0.1:9200"
            description: OpenSearch node addresses.
          username:
            type: str
            default: "admin"
            description: Username for OpenSearch.
          password:
            type: str
            description: Password for OpenSearch.
          tls:
            type: dict
            description: TLS configuration for OpenSearch output.
            options:
              enable:
                type: bool
                default: false
                description: Enable TLS.
              skip_verification:
                type: bool
                default: false
                description: Skip certificate verification.
              ca_cert_filepath:
                type: str
                default: ""
                description: Path to CA certificate.

          dashboards:
            type: dict
            description: |
              OpenSearch dashboard import configuration.
              See: https://docs.elastiflow.com/flowcoll/configuration/outputs/output_opensearch
            options:
              enable:
                type: bool
                default: false
                description: Enable OpenSearch dashboard import.
              url:
                type: str
                default: "https://raw.githubusercontent.com/elastiflow/elastiflow_for_opensearch/main/dashboards/flow/dashboards-2.14.x-flow-codex.ndjson"
                description: URL for OpenSearch dashboard.
              override:
                type: bool
                default: true
                description: Override existing dashboards.
              dashboards_url:
                type: str
                default: "http://127.0.0.1:5601"
                description: OpenSearch Dashboards URL.
              tls:
                type: dict
                description: TLS configuration for dashboard import.
                options:
                  validate_certs:
                    type: bool
                    default: false
                    description: Validate TLS certificates.
                  client_cert:
                    type: str
                    default: null
                    description: Path to client certificate.
                  client_key:
                    type: str
                    default: null
                    description: Path to client key.

      netobserv_flow_config_values:
        type: dict
        default: {}
        description: |
          Configuration values for NetObserv Flow. Values are appended to the `flowcoll.yml` as YAML.
          Example:
          ```yaml
          EF_LICENSE_ACCEPTED: "true"
          EF_SOME_SETTING: "/some/host/path/config.yml"
          EF_ANOTHER_SETTING: "/some/host/path/config.yml"
          ```

      netobserv_flow_kernel_parameters:
        type: dict
        description: |
          Kernel tuning parameters for NetObserv Flow.
          See: https://docs.elastiflow.com/flowcoll/installation/requirements#recommended-kernel-tuning
          ***defaults_prefix:"__"***
        options:
          tune_enabled:
            type: bool
            default: true
            description: Enable kernel tuning.
          net.core.netdev_max_backlog:
            type: int
            default: 4096
            description: Maximum number of packets allowed to queue when the interface receives packets faster than the kernel can process them.
          net.core.rmem_default:
            type: int
            default: 262144
            description: Default receive buffer size for network sockets.
          net.core.rmem_max:
            type: int
            default: 33554432
            description: |
              Maximum receive buffer size for network sockets.
              Related to [EF_FLOW_SERVER_UDP_READ_BUFFER_MAX_SIZE](https://docs.elastiflow.com/flowcoll/configuration/inputs/input_udp#ef_flow_server_udp_read_buffer_max_size)
          net.ipv4.udp_rmem_min:
            type: int
            default: 131072
            description: Minimum receive buffer size for UDP sockets.
          net.ipv4.udp_mem:
            type: str
            default: "2097152 4194304 8388608"
            description: Memory usage limits for UDP.
