- name: Render NetObserv Flow configuration
  ansible.builtin.template:
    src: "flowcoll.yml.j2"
    dest: "{{ netobserv_flow_config_file }}"
    mode: "0644"
    backup: true
  notify:
    - Restart NetObserv Flow
