# Ansible requirements to make ansible-lint GHA happy. List of roles and collections in the examples
collections:
  - name: community.general
  - name: community.docker
  - name: elastiflow.netobserv
roles:
  - name: geerlingguy.docker
