collections:
  - name: community.general
  - name: community.docker
  # TODO: Use Ansible Galaxy URL
  - name: elastiflow.netobserv
    type: git
    source: git@github.com:elastiflow/ansible-collection-netobserv.git
roles:
  - name: geerlingguy.docker
