---
- name: Install required packages with powertools repository
  ansible.builtin.dnf:
    name:
      - gnupg
      - ca-certificates
    state: present
    enablerepo: powertools
  when:
    - ansible_distribution_major_version == "8"
- name: Install required packages with crb repository
  ansible.builtin.dnf:
    name:
      - gnupg
      - ca-certificates
    state: present
    enablerepo: crb
  when:
    - ansible_distribution_major_version == "9"
- name: Add an ElastiFlow packages signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://elastiflow-releases.s3.us-east-2.amazonaws.com/elastiflow.pgp
    fingerprint: 6A2E 26EF DE24 AA7A 634A  442E D5C0 572E 5D21 2F6B
- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.copy:
    content: |
      [elastiflow-yum]
      name=elastiflow-yum
      baseurl=https://yum.elastiflow.com/elastiflow-yum
      enabled=1
      repo_gpgcheck=0
      gpgcheck=1
    dest: /etc/yum.repos.d/elastiflow.repo
    owner: "root"
    group: "root"
    mode: "0644"
- name: Install NetObserv Flow package
  ansible.builtin.dnf:
    name: "{{ collector_type }}-{{ version }}"
    state: present
